### ISSUE TITLE
setRegistrar: Missing documentation

### ISSUE THREAD

**Issue by GrandChaman** [zerolawtech/SFT-Protocol#57] opened 2019-09-03 13:44 UTC
Hello,

I noticed an odd behavior. When trying to `setRegistrar` from an `IssuingEntity` one must first disallow the registrar then allow it.
That's not documented and a bit counterintuitive.

👋

**Comment by nymd** [comment] 2019-09-03 15:13
Hello and thanks for trying out SFT.

Can you detail the steps to reproduce?

Using Brownie and the deployment script, the order of operations is:

def deploy_contracts(token_contract=SecurityToken):
    kyc = accounts[0].deploy(KYCRegistrar, [accounts[0]], 1)
    issuer = accounts[0].deploy(IssuingEntity, [accounts[0]], 1)
    token = accounts[0].deploy(token_contract, issuer, "Test Token", "TST", 1000000)
    issuer.addToken(token, {'from': accounts[0]})
    issuer.setRegistrar(kyc, False, {'from': accounts[0]})


The next step to allowing transfers would be to use setCountry and give a country an allowed limit of holders.

**Comment by GrandChaman** [comment] 2019-09-03 15:14
It's just no clear that we should be using `issuer.setRegistrar(kyc, False, {'from': accounts[0]})` instead of `issuer.setRegistrar(kyc, True, {'from': accounts[0]})` directly

**Comment by iamdefinitelyahuman** [comment] 2019-09-03 17:35
Seems to be a documentation issue:

https://github.com/zerolawtech/SFT-Protocol/blob/ca23e2199c469e760c0fcc4b02b844bb6a396135/contracts/IssuingEntity.sol#L286-L289

In the actual codebase, the boolean is `_restricted` but in the docs it's listed as `_permitted`.  Good catch!  Will update shortly.

**Comment by iamdefinitelyahuman** [comment] 2019-09-04 06:52
Docs have been corrected in #59, closing this issue.  If you run into anything else please let us know :)

**Closed by iamdefinitelyahuman** 2019-09-04 06:52 UTC
